---
title: "Untitled"
author: "김희수"
date: '2019 10 30 '
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plyr)
library(dplyr)
library(tidyverse)
library(mapdeck)
key = "pk.eyJ1IjoibHVuYXNlb3JpbSIsImEiOiJjazJjd3A0Z3IwajAzM2RvMjJvNWdqOGM5In0.C8bch4gbQBoRMccrAeCv8Q"
```

#---------------------------------------------------------------------------------------------------
###Visualising
```{r}
trans_table_fine1 <- read.csv("data/trans_table_fine1")

AAA <- trans_table_fine1[order(trans_table_fine1$freq,decreasing = T),]

AA <- AAA[1:10,]
rownames(AA)<-1:10

AA$org <- as.factor(AA$org)
AA$dst <- as.factor(AA$dst)
AA$id <- seq_len(nrow(AA))
AA$stroke <- sample(1:3, size = nrow(AA), replace = T)

mapdeck( token = key, style = mapdeck_style("dark"), pitch = 45 ) %>%
  add_arc(
data = AA
    , layer_id = "arc_layer"
    , origin = c("start_lon", "start_lat")
    , destination = c("end_lon", "end_lat")
    , stroke_from = "org"
    , stroke_to = "dst"
    , stroke_width = "stroke"
 )

```

