---
title: "머신러닝 - 생존분석 : Cox 비례위험모형"
author: "12조"
date: '2019 11 19 '
output: html_document
---

```{r setup, include=FALSE}
library(plyr)
library(dplyr)
library(ggplot2)
library(survival)
library(survminer)
library(caret)
library(survAUC)
```

## data

```{r data}
dat<-lung %>%
  na.omit() %>%
  data.frame()
```

##Cross Validation

```{r}
set.seed(1119)
q1<-dat[sample(nrow(dat))[1:55],]
q2<-dat[sample(nrow(dat))[56:111],]
q3<-dat[sample(nrow(dat))[112:167],]
train1 <- rbind(q1,q2)
test1 <- q3
train2 <- rbind(q2,q3)
test2 <- q1
train3 <- rbind(q1,q3)
test3 <- q2
```

## MODEL1(q1+q2)

```{r}
##1st : 하나가지고!
asys_1st <- NULL
for (i in 4:10) {
  a <- coxph(Surv(time,status==2)~dat[,i],data = dat)
  b <- rbind(asys_1st,
             data.frame(name = colnames(dat)[i],
                        coef = summary(a)$coefficients[1],
                        pvalue = summary(a)$coefficients[5]
                        )
             )
  asys_1st <- b
}

##2nd : 
coxph(Surv(time,status==2)~ph.ecog+pat.karno,data = dat)

asys_2nd <- NULL
for (i in c(4,5,7,9,10)) {
  a <- coxph(Surv(time,status==2)~ph.ecog+pat.karno+dat[,i],data = dat)
  b <- rbind(asys_2nd,
             data.frame(name = colnames(dat)[i],
                        coef = summary(a)$coefficients[3,1],
                        pvalue = summary(a)$coefficients[3,5]
                        )
             )
  asys_2nd <- b
}

##3rd : ph.ecog, ph.karno, sex
coxph(Surv(time,status==2)~ph.ecog+pat.karno+sex,data = dat)

asys_3rd <- NULL
for (i in c(4,7,9,10)) {
  a <- coxph(Surv(time,status==2)~ph.ecog+pat.karno+sex+dat[,i],data = dat)
  b <- rbind(asys_3rd,
             data.frame(name = colnames(dat)[i],
                        coef = summary(a)$coefficients[4,1],
                        pvalue = summary(a)$coefficients[4,5]
                        )
             )
  asys_3rd <- b
}

```

##그래프

```{r}
ggsurvplot(survfit(coxph(Surv(time,status==2)~ph.ecog+pat.karno+sex,data = dat)),data=dat,
           palette = "#2E9FDF",
           ggtheme = theme_minimal(),
           xlab = "Time(days)")
```

##propotional hazard 가정
`Proportional hazard 가정 (H0:비례위험 가정을 만족한다.)`

```{r}
cox.zph(pcox_step)
#p-value가 0.05이상이므로 H0 기각불가
```

##임시

```{r}
#모델링
full_model <- coxph(Surv(time,status==2)~.-inst,data = train3)
summary(full_model)

#ROC
pred <- predict(pcox_step)
pred_n <- predict(pcox_step,newdata = test2)
surv1 <- Surv(train1$time,train1$status)
surv1_n <- Surv(test1$time,test1$status)

AUC1 <- AUC.cd(surv1,surv1_n,pred,pred_n,seq(10,500,10))
plot(AUC1)
abline(h = 0.5)
#Gonen and Heller’s Concordance Index for Cox proportional hazards models
GHCI(pred_n)


```