---
title: 'bigdata mining : machine learning'
author: "김희수"
date: '2019 10 29 '
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(plyr)
library(dplyr)
library(doParallel)
library(tidygraph)
library(ggraph)
library(tidyverse)
library(mapdeck)
key = "pk.eyJ1IjoibHVuYXNlb3JpbSIsImEiOiJjazJjd3A0Z3IwajAzM2RvMjJvNWdqOGM5In0.C8bch4gbQBoRMccrAeCv8Q"
library(arules)
library(rgdal)
library(geosphere)

```

#병렬화

```{r}
detectCores()
cl <- makeCluster(7)
registerDoParallel(cl)

#병렬화 중지
stopCluster(cl)


```

## 데이터전처리

```{r cars}
A1 <- read.csv("data/PJT001_TripChain.csv")
A2 <- read.csv("data/PJT001_stations_table.csv")

B1 <- A1[A1$X...승차역ID1... == 4170316,]


a <- which(A2$시군명 == "화성시")

D1 <- A2[a,]

E1 <- data.frame()

rownames(D2) <- 1:1592

#동탄신도시
dongtan <- c("반송동", "석우동", "능동","영천동", "오산동", "청계동", "신동", "중동", "목동", "산척동", "방교동", "장지동", "금곡동", "송동")


##화성시 전체 승차(E2)
system.time(
E2 <- foreach(i=1:1592,.combine = rbind) %dopar% {
  b <- which(A1$X...승차역ID1...==D2$이비카드정류장ID[i])
  c <- A1[b,]
  return(c)
}
)

##화성시 동탄신도시 전체승차
#동탄신도시 버스정류장(dongtan_stop)
system.time(
dongtan_stop <- foreach (i=1:1592,.combine = rbind) %dopar% {
  d_logic <- any(substr(D2$위치[i],9,11) == dongtan)
  return(d_logic)
}
)

dongtan_stop <- D2[dongtan_stop,]

system.time(
dongtan_stop <- foreach (i=1:1592,.combine = rbind) %dopar% {
  d_logic <- any(substr(D2$위치[i],9,11) == dongtan)
  return(d_logic)
}
)

#동탄신도시 출발 태그기록(dongtan_tag)
rownames(dongtan_stop) <- 1:149
dongtan_stop$이비카드정류장ID <- as.numeric(dongtan_stop$이비카드정류장ID)
system.time(
dongtan_tag <- foreach (i=1:149,.combine = rbind) %dopar% {
  b <- which(A1$X...승차역ID1...==dongtan_stop$이비카드정류장ID[i])
  c <- A1[b,]
  return(c)
}
)

#동탄신도시 출발 0702~0704 07~09시
dongtan_tag_aa <- dongtan_tag[substr(dongtan_tag$X...최종하차일시...,8,8)==2|
  substr(dongtan_tag$X...최종하차일시...,8,8)==3|
  substr(dongtan_tag$X...최종하차일시...,8,8)==4,]

dongtan_tag_aa_morning <- dongtan_tag_aa[substr(dongtan_tag_aa$X...최종하차일시...,9,10)=="07"|
  substr(dongtan_tag_aa$X...최종하차일시...,9,10)=="08"|
  substr(dongtan_tag_aa$X...최종하차일시...,9,10)=="09",]

#동탄신도시 출발 0702~0704 17~19
dongtan_tag_aa_evening <- dongtan_tag_aa[substr(dongtan_tag_aa$X...최종하차일시...,9,10)=="17"|
  substr(dongtan_tag_aa$X...최종하차일시...,9,10)=="18"|
  substr(dongtan_tag_aa$X...최종하차일시...,9,10)=="19",]

#동탄신도시 도착 태그기록(dongtan_tag_dst)
system.time(
dongtan_tag_dst <- foreach (i=1:149,.combine = rbind) %dopar% {
  b <- which(A1$X...최종하차역ID...==dongtan_stop$이비카드정류장ID[i])
  c <- A1[b,]
  return(c)
}
)

#동탄신도시 도착 0702~0704 07~09시
dongtan_tag_dst_aa <- dongtan_tag[substr(dongtan_tag_dst$X...최종하차일시...,8,8)==2|
  substr(dongtan_tag_dst$X...최종하차일시...,8,8)==3|
  substr(dongtan_tag_dst$X...최종하차일시...,8,8)==4,]

dongtan_tag_dst_morning <- dongtan_tag_dst_aa[substr(dongtan_tag_dst_aa$X...최종하차일시...,9,10)=="07"|
  substr(dongtan_tag_dst_aa$X...최종하차일시...,9,10)=="08"|
  substr(dongtan_tag_dst_aa$X...최종하차일시...,9,10)=="09",]

#동탄신도시 도착 0702~0704 17~19
dongtan_tag_dst_evening <- dongtan_tag_aa[substr(dongtan_tag_dst_aa$X...최종하차일시...,9,10)=="17"|
  substr(dongtan_tag_dst_aa$X...최종하차일시...,9,10)=="18"|
  substr(dongtan_tag_dst_aa$X...최종하차일시...,9,10)=="19",]




#동탄내 이동 태그기록
dongtan_tag_ext <- data.frame()
system.time(
dongtan_tag_ext <- foreach (i=1:149,.combine = rbind) %dopar% {
  a <- which(dongtan_tag_dst$X...승차역ID1...==dongtan_stop$이비카드정류장ID[i])
  b <- dongtan_tag_dst[a,]
  c <- which(dongtan_tag$X...승차역ID1...==dongtan_stop$이비카드정류장ID[i])
  d <- dongtan_tag[c,]
  e <- rbind(b,d)
  unique(e)
}
)

#동탄내 ext_morning
dongtan_tag_ext_aa <- dongtan_tag[substr(dongtan_tag_ext$X...최종하차일시...,8,8)==2|
  substr(dongtan_tag_ext$X...최종하차일시...,8,8)==3|
  substr(dongtan_tag_ext$X...최종하차일시...,8,8)==4,]

dongtan_tag_ext_evening <- dongtan_tag_ext_aa[substr(dongtan_tag_ext_aa$X...최종하차일시...,9,10)=="17"|
  substr(dongtan_tag_ext_aa$X...최종하차일시...,9,10)=="18"|
  substr(dongtan_tag_ext_aa$X...최종하차일시...,9,10)=="19",]

dongtan_tag_ext_morning

#동탄내 구간 morning
move_total <- dongtan_tag_ext_evening[,c(37,48)] %>%
  `colnames<-`(c("org","dst"))
move_total<-move_total[nchar(move_total$org)>6&nchar(move_total$dst)>6,]

move_total <- paste0(move_total$org,",",move_total$dst)
trans_table<-as.data.frame(table(move_total))

trans_table <- data.frame(org = substr(trans_table$move_total,1,7),
                          dst = substr(trans_table$move_total,9,15),
                          freq = trans_table$Freq)

dongtan_tag_ext$

```

## 하차역

```{r pressure, echo=FALSE}
#m_down 최종하차역 통계(최초승차역은 동탄)
m_down <- data.frame(table(dongtan_tag$X...최종하차역ID...))
m_down$name <- NA

system.time(
m_down_name <- foreach (i=1:3369,.combine = rbind) %dopar% {
  a1 <- which(m_down$Var1[i] == A2$이비카드정류장ID)
  ifelse(length(a1)>0,
         ifelse(length(A2$정류소명[a1])>0,
                m_down$name[i] <- as.character(A2$정류소명[a1]),
                m_down$name[i] <- "미등록"),
         m_down$name[i] <- "미등록")
}
)
m_down$name <- m_down_name

#m_down_morning
m_down_morning <- data.frame(table(dongtan_tag_aa_morning$X...최종하차역ID...))
m_down_morning$name <- NA

system.time(
m_down_name <- foreach (i=1:1429,.combine = rbind) %dopar% {
  a1 <- which(m_down_morning$Var1[i] == A2$이비카드정류장ID)
  ifelse(length(a1)>0,
         ifelse(length(A2$정류소명[a1])>0,
                m_down_morning$name[i] <- as.character(A2$정류소명[a1]),
                m_down_morning$name[i] <- "미등록"),
         m_down_morning$name[i] <- "미등록")
}
)
m_down_morning$name <- m_down_name

#m_down_evening
m_down_evening <- data.frame(table(dongtan_tag_aa_evening$X...최종하차역ID...))
m_down_evening$name <- NA

system.time(
m_down_name <- foreach (i=1:1453,.combine = rbind) %dopar% {
  a1 <- which(m_down_evening$Var1[i] == A2$이비카드정류장ID)
  ifelse(length(a1)>0,
         ifelse(length(A2$정류소명[a1])>0,
                m_down_evening$name[i] <- as.character(A2$정류소명[a1]),
                m_down_evening$name[i] <- "미등록"),
         m_down_evening$name[i] <- "미등록")
}
)
m_down_evening$name <- m_down_name

#m_up 최초승차역 통계(최종하차역은 동탄)
m_up <- data.frame(table(dongtan_tag_dst$X...승차역ID1...))
m_up$name <- NA

system.time(
m_up_name <- foreach (i=1:3101,.combine = rbind) %dopar% {
  a1 <- which(m_up$Var1[i] == A2$이비카드정류장ID)
  ifelse(length(a1)>0,
         ifelse(length(A2$정류소명[a1])>0,
                m_up$name[i] <- as.character(A2$정류소명[a1]),
                m_up$name[i] <- "미등록"),
         m_up$name[i] <- "미등록")
}
)
m_up$name <- m_up_name

#m_up_morning
m_up_morning <- data.frame(table(dongtan_tag_dst_morning$X...승차역ID1...))
m_up_morning$name <- NA

system.time(
m_up_name <- foreach (i=1:129,.combine = rbind) %dopar% {
  a1 <- which(m_up_morning$Var1[i] == A2$이비카드정류장ID)
  ifelse(length(a1)>0,
         ifelse(length(A2$정류소명[a1])>0,
                m_up_morning$name[i] <- as.character(A2$정류소명[a1]),
                m_up_morning$name[i] <- "미등록"),
         m_up_morning$name[i] <- "미등록")
}
)
m_up_morning$moring <- m_up_name

#m_up_evening
m_up_evening <- data.frame(table(dongtan_tag_dst_evening$X...승차역ID1...))
m_up_evening$name <- NA

system.time(
m_up_name <- foreach (i=1:137,.combine = rbind) %dopar% {
  a1 <- which(m_up_evening$Var1[i] == A2$이비카드정류장ID)
  ifelse(length(a1)>0,
         ifelse(length(A2$정류소명[a1])>0,
                m_up_evening$name[i] <- as.character(A2$정류소명[a1]),
                m_up_evening$name[i] <- "미등록"),
         m_up_evening$name[i] <- "미등록")
}
)
m_up_evening$name <- m_up_name
```


#전구간 전처리(환승구간 포함)

```{r}
total_trans <- data.frame(org = NA,dst=NA)
system.time(
total_trans <- foreach (i=1:58150,.combine = rbind) %dopar% {
a <- ifelse(is.na(dongtan_tag[i,40]),
       ifelse(is.na(dongtan_tag[i,39]),
              ifelse(is.na(dongtan_tag[i,38]),
                     a<-37,a<-38),a<-39),a<-40)
ifelse(a==39,a1<-data.frame(org = as.numeric(dongtan_tag[i,37:39]),dst = as.numeric(dongtan_tag[i,c(38,39,48)])),
ifelse(a==38,a1<-data.frame(org = as.numeric(dongtan_tag[i,37:38]),dst = as.numeric(dongtan_tag[i,c(38,48)])),
ifelse(a==37,a1<-data.frame(org = as.numeric(dongtan_tag[i,37]),dst = as.numeric(dongtan_tag[i,48])))))
a1
})

total_trans<-total_trans[nchar(total_trans$org)>6&nchar(total_trans$dst)>6,]

trans_table <- paste0(total_trans$org,",",total_trans$dst)
trans_table<-as.data.frame(table(trans_table))

trans_table <- data.frame(org = substr(trans_table$trans_table,1,7),
                          dst = substr(trans_table$trans_table,9,15),
                          freq = trans_table$Freq)

trans_table <- data.frame(table(c(total_trans$org,total_trans$dst)))
i=132
system.time(
name1 <- foreach (i=1:3218,.combine = rbind) %dopar% {
  a1 <- which(trans_table[i,1] == A2$이비카드정류장ID)
  ifelse(length(a1)>0,
         ifelse(length(A2$정류소명[a1])>0,
                trans_table$name[i] <- as.character(A2$정류소명[a1]),
                trans_table$name[i] <- "미등록"),
         trans_table$name[i] <- "미등록")
}
)

trans_table<-data.frame(table(c(total_trans$org,total_trans$dst)))
View(trans_table)
hist(trans_table$Freq)

```

#구간 시각화

```{r}
move_total <- dongtan_tag[,c(37,48)] %>%
  `colnames<-`(c("org","dst"))
move_total<-move_total[nchar(move_total$org)>6&nchar(move_total$dst)>6,]

move_total <- paste0(move_total$org,",",move_total$dst)
trans_table <- as.data.frame(table(move_total))

trans_table <- data.frame(org = substr(trans_table$move_total,1,7),
                          dst = substr(trans_table$move_total,9,15),
                          freq = trans_table$Freq)
##전처리
end_location <- data.frame()
system.time(
start_location <-foreach(i=1:3218,.combine = rbind) %dopar%{
a <- which(trans_table[i,1] == A2$이비카드정류장ID)
b <- A2[a,9:10]
ifelse(nrow(b)>0,
       c <- b,
       c <- data.frame(WGS84위도="미등록",WGS84경도="미등록"))
c
})

trans_table<-cbind(trans_table,start_location,end_location)

trans_table_fine1<-read.csv("data/trans_table_fine1")
colnames(trans_table_fine1)[5:8]<-c("start_lat","start_lon","end_lat","end_lon")
rownames(trans_table) <- 1:13613
trans_table_fine <- trans_table[-which(trans_table$start_lat == "미등록"|
                                         trans_table$start_lon == "미등록"|
                                         trans_table$end_lat == "미등록"|
                                         trans_table$end_lon == "미등록"),]

rownames(trans_table_fine) <- 1:11808
trans_table_fine1 <- trans_table_fine[-which(is.na(trans_table_fine$end_lat)),]
rownames(trans_table_fine1) <- 1:11315

trans_table_fine1$start_lat<-as.numeric(trans_table_fine1$start_lat)

t_t_fine <- trans_table_fine1[order(trans_table_fine1$freq,decreasing = T),]
t_t_fine <- t_t_fine[1:100,]
t_t_fine$freq<-t_t_fine$freq/204+1
mapdeck( token = key, style = mapdeck_style("dark"), pitch = 15 ) %>%
add_arc(
data = t_t_fine
, layer_id = "arc_layer"
, origin = c("start_lon", "start_lat")
, destination = c("end_lon", "end_lat")
, stroke_from = "org"
, stroke_to = "dst"
, stroke_width = 3
)

#전체기록
alltag<-data.frame(org=A1$X...승차역ID1...,dst=A1$X...최종하차역ID...)

alltag_over6 <- alltag[nchar(alltag$org)>6&nchar(alltag$dst)>6,]

alltag_over6 <- paste0(alltag_over6$org,",",alltag_over6$dst)
trans_alltag <- as.data.frame(table(alltag_over6))

trans_alltag <- data.frame(org = substr(trans_alltag$alltag_over6,1,7),
                           dst = substr(trans_alltag$alltag_over6,9,15),
                           freq = trans_alltag$Freq)
trans_alltag <- trans_alltag[-263030,]

trans_alltag <- trans_alltag[order(trans_alltag$freq,decreasing = T),] %>%
  `rownames<-`(1:263029)

trans_alltag_a <- trans_alltag[1:500,]

system.time(
start_location <-foreach(i=1:500,.combine = rbind) %dopar%{
  a <- which(trans_alltag_a[i,1] == A2$이비카드정류장ID)
  b <- A2[a,9:10]
  ifelse(nrow(b)>0,
         c <- b,
         c <- data.frame(WGS84위도="미등록",WGS84경도="미등록"))
  c
})

system.time(
end_location <-foreach(i=1:500,.combine = rbind) %dopar%{
a <- which(trans_alltag_a[i,2] == A2$이비카드정류장ID)
b <- A2[a,9:10]
ifelse(nrow(b)>0,
       c <- b,
       c <- data.frame(WGS84위도="미등록",WGS84경도="미등록"))
c
})

table_alltag <- cbind(trans_alltag_a,start_location,end_location) %>%
  `colnames<-`(c("org","dst","freq","start_lat","start_lon","end_lat","end_lon"))

table_alltag <- table_alltag[!table_alltag$end_lat=="미등록",]

table_alltag <- as.data.frame(apply(table_alltag, 2, as.numeric))

mapdeck( token = key, style = mapdeck_style("dark"), pitch = 25 ) %>%
add_arc(
data = table_alltag
, layer_id = "arc_layer"
, origin = c("start_lon", "start_lat")
, destination = c("end_lon", "end_lat")
, stroke_from = "org"
, stroke_to = "dst"
, stroke_width = 3
)




```

##구간빈도수

```{r}
move_total <- dongtan_tag_aa_morning[,c(37,48)] %>%
  `colnames<-`(c("org","dst"))
move_total<-move_total[nchar(move_total$org)>6&nchar(move_total$dst)>6,]

move_total <- paste0(move_total$org,",",move_total$dst)
trans_table<-as.data.frame(table(move_total))

trans_table <- data.frame(org = substr(trans_table$move_total,1,7),
                          dst = substr(trans_table$move_total,9,15),
                          freq = trans_table$Freq)

trans_table<-trans_table[order(trans_table$freq,decreasing=T),] %>%
  `rownames<-`(1:3949)

finally_we_find <- trans_table[1:2,]




```

##굴곡도

```{r}
#map_link
geo_sd <- st_read("data/PJT001_moc_link_2018.geojson")
geo_se_df <- as.data.frame(st_coordinates(geo_sd))

mapdeck( token = key, style = mapdeck_style("dark"), pitch = 25 ) %>%
add_path(
data = geo_sd
, layer_id = "path_layer"
, tooltip = "L2"
)

#버스노선_정류장
bus_line <- read.csv("data/경기도_화성시_마을버스현황_20190502.csv")

bus_line_17 <- bus_line[bus_line$노선번호==17,]

#굴곡도
nord_curv <- function(q){
  b1 <- bus_line[bus_line$노선번호==q,]
  e <-NULL
for (i in 1:nrow(b1)) {
  b2 <- sqrt((gulgok1[i,10]-gulgok1[i+1,10])^2+(gulgok1[i,11]-gulgok1[i+1,11])^2)*100000
  e <- c(e,b2)
  e
}
  leng <-c(0,e[1:nrow(b1)-1])
 cbind(b1,leng)
}

```

#굴곡도 by tag

```{r}
a = 17
gulgok1 <- nord_curv(50)

c1 <- sum(gulgok1$구간거리)
c2 <- sqrt((gulgok1[1,10]-gulgok1[nrow(gulgok1),10])^2+(gulgok1[1,11]-gulgok1[nrow(gulgok1),11])^2)*100000
c1/c2


gul_func(gulgok1)

final <- read.csv("data/aaaaa.csv")
final$num <- 1:40

which(final$id == A2$정류소번호)

system.time(
finally_we_find <-foreach(i=1:40,.combine = rbind) %dopar%{
a <- which(final$id[i] == A2$정류소번호)
b <- A2[a,c(3,5,9:10)]
b
})

final_fine <- merge(x=final,y=finally_we_find,by.x="id",by.y="정류소번호",all.x=T)

final_match <- final$id

finalfineaaa$WGS84위도 <- as.numeric(finalfineaaa$WGS84위도)
c1<-NULL
c2 <- NULL
for (i in 1:40) {
  c2[i] <- sqrt((finalfineaaa[i,5]-finalfineaaa[i+1,5])^2+(finalfineaaa[i,6]-finalfineaaa[i+1,6])^2)*100000
}
c1 <- sum(finalfineaaa$leng)
c2 <- sqrt((finalfineaaa[1,5]-finalfineaaa[nrow(finalfineaaa),5])^2+(finalfineaaa[i,6]-finalfineaaa[i=1,11])^2)*100000
c1/c2 #전체굴곡도

a <- finalfineaaa$leng[2:40]/finalfineaaa$asdf[2:40]
a[a<0]

ok <- data.frame(id = c(36406,36345,37662),
                 lon = c(37.23063) ,
                 lat = c(127.0681),
                 leng = c(4900))
37.23063,127.0681
37.20692,127.0356
37.19312,127.0731

(sqrt((37.19715-37.20692)^2+(127.0726-127.0356)^2)*100000)
(sqrt((37.20692-37.19312)^2+(127.0356-127.0731)^2)*100000)

#1-2 3903
4900/3903
#2-3 3659
5700/3659
#3-1 4194
5100/4194
```
